### ISSUE TITLE
I want to create swift playground in the current directory I am in

### ISSUE THREAD

**Issue by nikivdev** [JohnSundell/Playground#1]
For example if I was in `~/swift/`  and I would run `playground new_playground` it would create new_playground in the directory I am in. I am not really sure what I should change in the script to make that happen.

Thank you for any help.

**Comment by JohnSundell** [comment]
He @nikitavoloboev! I've now rewritten `playground` in Swift, and the feature you're looking for is supported. Simply use the `-t` argument to give a target path to create a playground at 🎉
