### ISSUE TITLE
Bug: Can't compile with Marathon

### ISSUE THREAD

**Issue by skagedal** [JohnSundell/Playground#18]
```
➜  mint install JohnSundell/Marathon  
🌱  Finding latest version of Marathon
🌱  Cloning Marathon 3.1.0
🌱  Resolving package
🌱  Building package
🌱  Installed Marathon 3.1.0
🌱  Linked Marathon 3.1.0 to /usr/local/bin
➜  marathon install JohnSundell/playground
🏃  Cloning https://github.com/JohnSundell/playground.git...
   Compiling script...
💥  Failed to compile script
➜  xcode-select -p
/Applications/Xcode 10.1.app/Contents/Developer
➜  
```

Is there a way to get the build output from marathon?

**Comment by skagedal** [comment]
Ah, actually I think this is the source of the problem, which happened the first time I run it (and could reproduce after cleaning `~/.marathon`):

```
➜  mv ~/.marathon ~/.marathon-foo
➜  marathon install JohnSundell/playground
🏃  Cloning https://github.com/JohnSundell/playground.git...
   Updating packages...
   Cloning https://github.com/JohnSundell/Xgen.git...
   Resolving latest major version for https://github.com/JohnSundell/Xgen.git...
   Updating packages...
   Cloning https://github.com/JohnSundell/Files.git...
   Resolving latest major version for https://github.com/JohnSundell/Files.git...
   Updating packages...
💥  Failed to update packages
👉  Make sure you have write permissions to the folder '/Users/simon/.marathon/Packages/'
```
Why though? I do, of course, have permissions.

**Comment by skagedal** [comment]
FWIW I could compile fine using direct clone and SPM (as per README instructions)

**Comment by muyexi** [comment]
I have to `xcode-select` Xcode 10.1 to install Playground using SPM, otherwise I get a lot of errors from `swift build`.

**Comment by Randoramma** [comment]
For installation I was able to follow muyexi's advice and switch from my current version of Xcode (11.2.1) to Xcode 10.1 via Xcode select and install following the SPM instructions.. Then I was able to  Xcode select back to latest Xcode and everything worked fine.  Thanks!

**Comment by JohnSundell** [comment]
Sorry, but this won't be fixed, since Marathon is now deprecated and archived. I recommend installing Playground using the Swift Package Manager instead.
