### ISSUE TITLE
playground build hanging

### ISSUE THREAD

**Issue by phildrone** [JohnSundell/Playground#3]
At the build step, I ran the proscribed commands:

$ git clone git@github.com:JohnSundell/Playground.git  (this worked)
$ cd Playground/ (obviously this did too)
$ swift build -c release -Xswiftc -static-stdlib  (hung here)
Fetching git@github.com:johnsundell/files.git

And hangs at this point, under fetching. No release is built, and I ended up killing it after letting it sit there for about an hour. Tried multiple times, no luv.

**Comment by JohnSundell** [comment]
@phildrone Hi! Could you provide the following information to help me debug this issue:

- Do you have an SSH key setup with GitHub?
- What version of Xcode and Swift are you on?

**Comment by phildrone** [comment]
Yes, but good point about the SSH key. I do have an ssh key setup with GitHub, but I am not using an ssh-agent bash type shell. Just tried it inside the ssh-agent shell and that didn't work either. Worth a shot. Xcode 8.3.1, Swift 3.1.

**Comment by phildrone** [comment]
Ooop, that was it, forgot the ssh-add step. Once I added it, the build started working. Thank you!

**Comment by phildrone** [comment]
All set.

**Comment by JohnSundell** [comment]
@phildrone No worries! Hope you enjoy Playground! 😄

**Comment by phildrone** [comment]
Just got it up and running, but already I can tell I’ll be using this quite a bit! Thank you!

Phil
