### ISSUE TITLE
marathon install hanging

### ISSUE THREAD

**Issue by cameroncooke** [JohnSundell/Playground#4]
I've just tried to install the new Swift version of Playground using the Marathon install method but it's just hanging at the Cloning step:

```
🏃  Downloading script...
   Saving script...
   Resolving Marathonfile...
   Saving Marathonfile...
   Cloning git@github.com:johnsundell/xgen.git...
```

It's been like this now for a couple of hours. This is my second attempt too, I tried before and had the same problem and had to cancel.

|Git|OSX|Shell|Swift|Xcode|
|-|-|-|-|-|
| 2.11.0 (Apple Git-81) | 10.12.4 (16E195) | ZSH | 3.1 (swiftlang-802.0.51 clang-802.0.41) |  8.3.1 (8E1000a) |

**Comment by JohnSundell** [comment]
@cameroncooke Do you have an SSH-key setup with GitHub?

**Comment by cameroncooke** [comment]
Yes!?

**Comment by cameroncooke** [comment]
Got it, it was non-interactively asking for the passphrase. Sorted.

**Comment by JohnSundell** [comment]
@cameroncooke Awesome! I'm adding a `--verbose` option to Marathon as we speak, which should make debugging these kind of issues a lot easier (it displays all the underlying shell commands that Marathon issues).

**Comment by cameroncooke** [comment]
Great idea, also could be useful to mention this on the installation instructions for Playground. Thanks.

**Comment by JohnSundell** [comment]
@cameroncooke Will do, as soon as it's released 👍

**Comment by mihaicris** [comment]
@cameroncooke How did you solve it? I have configured my ssh public key from ~/.ssh/id_rsa.pub to GitHub, and still it is not working either form Terminal or Xterm2.

Fetching git@github.com:johnsundell/files.git
-- nothing ---

**Comment by cameroncooke** [comment]
I used this command `ssh-add -K ~/.ssh/id_rsa &>/dev/null` to prevent further pass-phrase authentication challenges before issuing `marathon install`

**Comment by mihaicris** [comment]
Solved. Thanks.
