### ISSUE TITLE
Feature Request: Cocoapods support

### ISSUE THREAD

**Issue by pepejeria** [JohnSundell/Playground#5]
Would be great if Playground supported to Cocoapods to easily add third-party frameworks.

**Comment by JohnSundell** [comment]
@pepejeria I've now created a separate tool for that - it's called Test Drive, and lets you open a Playground for any Swift pod or framework 😄 https://github.com/johnsundell/testdrive.

**Comment by pepejeria** [comment]
Oh. That's awesome, thanks
