### ISSUE TITLE
git clone command

### ISSUE THREAD

**Issue by rpural** [JohnSundell/Playground#7]
In the instructions at the bottom of the README, shouldn't the proper clone command be:

git clone https://github.com/JohnSundell/Playground.git

The command you show fails.

**Comment by JohnSundell** [comment]
@rpural The command in the README uses the SSH-based cloning URL, which works perfectly if you have SSH keys setup with GitHub. I agree though that it's probably better to show the HTTPS-based one since not everyone uses SSH. Do you want to submit a PR that fixes this issue?

**Comment by JohnSundell** [comment]
Fixed it
