### ISSUE TITLE
Default Playground Path creating unintended folders

### ISSUE THREAD

**Issue by felix-dumit** [JohnSundell/Playground#9]
I am using the tool without specifying any target path parameters.
By default it will assume the path to be like this (depending on date):
 "~/Desktop/12/31/17.playground"

This results in there being a "12" folder, then a "31" folder and then the file "17.playground" inside it.
I think this is not the intended behavior.

A possible solution would be to change the date formatter to use something like:         `formatter.dateFormat = "MM-dd-yy"`

It would also be nice if the default path was `"~/Desktop/Playgrounds/\(Date().today)"` instead of just desktop. (optionally this could be a configurable setting)

**Comment by franciscoamado** [comment]
Hi there!

Totally agree with you and it does seems to be a bug since the default for _Target Path_ is `Default: ~/Desktop/<Date>`! 

I actually find your suggestion much better, avoids folder pits.

@johnsundell what do you think about this?

**Comment by Ashton-W** [comment]
I believe this behaviour is not intended. In this animated GIF tweeted by @JohnSundell himself, you can see the path uses dashes not slashes in the date format. Depending on the Locale of your Mac, you'll get dashes, periods, or slashes. Unfortunately slashes means you'll create lots of directories.

https://twitter.com/johnsundell/status/959861172185989121

<img width="503" alt="screen shot 2018-02-10 at 2 40 15 pm" src="https://user-images.githubusercontent.com/1650398/36058295-66b18f36-0e70-11e8-9ce7-1c829a0b7a7d.png">
